<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit28d020e0a41b2d54874d6b1ab2ece5bb
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('RoadmapStarter\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \RoadmapStarter\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit28d020e0a41b2d54874d6b1ab2ece5bb', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \RoadmapStarter\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit28d020e0a41b2d54874d6b1ab2ece5bb', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\RoadmapStarter\Vendor\Composer\Autoload\ComposerStaticInit28d020e0a41b2d54874d6b1ab2ece5bb::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
