<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\' => array($vendorDir . '/stoutlogic/acf-builder/src'),
    'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/src'),
);
