<?php

// autoload_static.php @generated by Composer

namespace RoadmapStarter\Vendor\Composer\Autoload;

class ComposerStaticInit28d020e0a41b2d54874d6b1ab2ece5bb
{
    public static $prefixLengthsPsr4 = array (
        'R' =>
        array (
            'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\' => 44,
            'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\' => 41,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\' =>
        array (
            0 => __DIR__ . '/..' . '/stoutlogic/acf-builder/src',
        ),
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\' =>
        array (
            0 => __DIR__ . '/..' . '/doctrine/inflector/src',
        ),
    );

    public static $classMap = array (
        'RoadmapStarter\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\CachedWordInflector' => __DIR__ . '/..' . '/doctrine/inflector/src/CachedWordInflector.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\GenericLanguageInflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/GenericLanguageInflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Inflector' => __DIR__ . '/..' . '/doctrine/inflector/src/Inflector.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Language' => __DIR__ . '/..' . '/doctrine/inflector/src/Language.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\LanguageInflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/LanguageInflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\NoopWordInflector' => __DIR__ . '/..' . '/doctrine/inflector/src/NoopWordInflector.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\English\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/English/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\English\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/English/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\English\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/English/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\English\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/English/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Esperanto\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Esperanto/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Esperanto\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Esperanto/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Esperanto\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Esperanto/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Esperanto\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Esperanto/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\French\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/French/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\French\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/French/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\French\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/French/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\French\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/French/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Italian\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Italian/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Italian\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Italian/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Italian\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Italian/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Italian\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Italian/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\NorwegianBokmal\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/NorwegianBokmal/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\NorwegianBokmal\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/NorwegianBokmal/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\NorwegianBokmal\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/NorwegianBokmal/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\NorwegianBokmal\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/NorwegianBokmal/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Pattern' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Pattern.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Patterns' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Patterns.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Portuguese\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Portuguese/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Portuguese\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Portuguese/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Portuguese\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Portuguese/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Portuguese\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Portuguese/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Ruleset' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Ruleset.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Spanish\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Spanish/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Spanish\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Spanish/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Spanish\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Spanish/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Spanish\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Spanish/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Substitution' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Substitution.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Substitutions' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Substitutions.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Transformation' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Transformation.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Transformations' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Transformations.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Turkish\\Inflectible' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Turkish/Inflectible.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Turkish\\InflectorFactory' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Turkish/InflectorFactory.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Turkish\\Rules' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Turkish/Rules.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Turkish\\Uninflected' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Turkish/Uninflected.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\Rules\\Word' => __DIR__ . '/..' . '/doctrine/inflector/src/Rules/Word.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\RulesetInflector' => __DIR__ . '/..' . '/doctrine/inflector/src/RulesetInflector.php',
        'RoadmapStarter\\Vendor\\Doctrine\\Inflector\\WordInflector' => __DIR__ . '/..' . '/doctrine/inflector/src/WordInflector.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\AccordionBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/AccordionBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Builder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Builder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\ChoiceFieldBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/ChoiceFieldBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\ConditionalBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/ConditionalBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FieldBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FieldBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FieldManager' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FieldManager.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FieldNameCollisionException' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FieldNameCollisionException.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FieldNotFoundException' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FieldNotFoundException.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FieldsBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FieldsBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\FlexibleContentBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/FlexibleContentBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\GroupBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/GroupBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\LayoutNotFoundException' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/LayoutNotFoundException.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\LocationBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/LocationBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\ModifyFieldReturnTypeException' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/ModifyFieldReturnTypeException.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\NamedBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/NamedBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\ParentDelegationBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/ParentDelegationBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\RepeaterBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/RepeaterBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\TabBuilder' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/TabBuilder.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Traits\\CanSingularize' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Traits/CanSingularize.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\ConditionalField' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/ConditionalField.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\ConditionalLogic' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/ConditionalLogic.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\FlexibleContentLayout' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/FlexibleContentLayout.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\IterativeTransform' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/IterativeTransform.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\NamespaceFieldKey' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/NamespaceFieldKey.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\RecursiveTransform' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/RecursiveTransform.php',
        'RoadmapStarter\\Vendor\\StoutLogic\\AcfBuilder\\Transform\\Transform' => __DIR__ . '/..' . '/stoutlogic/acf-builder/src/Transform/Transform.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit28d020e0a41b2d54874d6b1ab2ece5bb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit28d020e0a41b2d54874d6b1ab2ece5bb::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit28d020e0a41b2d54874d6b1ab2ece5bb::$classMap;

        }, null, ClassLoader::class);
    }
}
